site_name: Munish(s) Blog
site_description: >-
  A professional blog showcasing business problem solutions.
theme:
  name: material
  features:
    - navigation.sections
    - content.code.annotate
    - content.code.copy
  pygments_style: github
  logo: null
  favicon: null
  homepage: index.md
plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
nav:
  - Home: index.md
  - Entra:
      - Certificate Based Authentication: azure-ad-certificate/index.md
  - SAP:
      - Setup PyRFC in your Container: sap-rfc-python-container/index.md
extra_css:
  - assets/custom.css
extra_javascript:
  - assets/custom.js
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
