site_name: My Technical Blog
site_description: >-
  A professional blog showcasing business problem solutions with Python, Azure, and PowerShell examples.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.code.copy
plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
nav:
  - Home: index.md
  - Sample Blog Article:
      - Article: sample-blog-article/index.md
