site_name: Munish(s) Blog
site_description: >-
  A professional blog showcasing business problem solutions.
site_url: https://munishsethi.com/
theme:
  name: material
  features:
    - navigation.sections
    - content.code.annotate
    - content.code.copy
  pygments_style: github
  logo: null
  favicon: null
  homepage: index.md
plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
nav:
  - Home: index.md
  - Azure:
      - Certificate Based Authentication: azure-ad-certificate.md
      - Download Azure Bill: azure-billing.md
      - Download Azure Resource: azure-resources.md
      - Query Recovery Services Vault: azure-query-recovery-services-vault.md
      - Entra Users, User Groups and Licence assignments: azure-ad-user.md
      - Entra User Devices: azure-ad-user-devices.md
      - Orchestrating Scheduled Jobs (Container Instances): azure-container-schedule.md
      - DevOps Build Container: devops-build-container.md
      - DevOps Deploy Container IaC: devops-deploy-container-iac.md
      - DevOps Deploy Container Github Actions: devops-deploy-container-github-action.md
      - Building and Publishing an Custom Image: avd-custon-image-compute-gallery-part1.md
      - Deploying Azure Virtual Desktop (AVD) Desktops: avd-publish-part2.md
      - Cleanup Obsolete FXLogix Profiles(AVD): avd-cleanup-obsolete-fsLogix-profiles.md
      - Business Coninuity Program / Diasister Recovery - Part 1: azure-bcpdr-part1.md
      - Business Continuity Program / Disaster Recovery - Part 2: azure-bcpdr-part2.md
      - Business Continuity Program / Disaster Recovery - Git Hub Action: azure-bcpdr-github-action.md
      - Restore VM from RSV Backup - Part 1: azure-restore-from-backup-part1.md
      - Restore VM from RSV Backup - Part 2: azure-restore-from-backup-part2.md

  - Fabric:
      - Warehouse data import: fabric-wharehouse-fact-import.md
  - Cisco Meraki, Nagios XI & Manage Engine:
      - Cisco Meraki Unused Devices : meraki-unused-device-sync.md
      - Cisco Meraki Devices Discovery and Nagios Integration: meraki-nagios-device-sync.md
      - Integrating Monitoring System with ITSM System: monitoring-itsm-integration.md
      - Deploying Cisco Meraki vMX: meraki-vm-deployment.md
  - Active Directory Domain Services:
      - Create ADDS User: adds-user-creation.md
      - Update ADDS User: adds-user-update.md
  - SAP:
      - Setup PyRFC in your Container: sap-rfc-python-container.md
      - Calling SAP RFC Function Modules from Python: sap-rfc-python.md
      - Automating SAP System Start/Stop Operations: sap-system-start-stop.md
  - O365:
      - Outlook Actionable Adaptive Card - Part 1: adaptive-card-consultant-review-part1.md
      - Outlook Actionable Adaptive Card - Part 2: adaptive-card-consultant-review-part2.md
      - Sharepoint Sites Enumeration: sharepoint-sites-enumeration.md
      - Sharepoint Document Library Enumeration: sharepoint-site-library-enumeration.md
      - Migrate Sharepoint Document Library to Azure File Share: sharepoint-site-library-to-azure-fileshare.md
      - Concur Expense Report Aggregation: sap-concur-expense-reports-aggregation.md
      - Get all Teams Phone Assignment(s): teams-user-number-assignment.md
      - Deprovison User: deprovision-user.md
      - Tenant Allow Block List - False Positive: tenantallowblocklist.md
      - O365 and Proof Point Essentials - Part 1: email-o365-proofpoint-part1.md
      - O365 and Proof Point Essentials - Part 2: email-o365-proofpoint-part2.md
      - O365 and Proof Point Essentials - Part 3: email-o365-proofpoint-part3.md
      - O365 and Proof Point Essentials - Part 4: email-o365-proofpoint-part4.md
      - O365 and Proof Point Essentials - Part 5: email-o365-proofpoint-part5.md
  - UKG:
      - Secure File Transfer with UKG Dimensions: ukg-sftp-file-transfer.md
      - Employee Verification via API: ukg-api-employee-verification.md
      - Automating Integration Execution and Dataview extract: ukg-api-integration-and-dataview.md
  
  - Misc:
      - Proof Point User Management: proofpoint-user-management.md
      - Clean GitHub Deployments: github-clean-deployments.md
      - Understanding DMARC/Spoofing, O365 with ProofPoint: proofpointo365connector.md

extra:
  description: "Munish Sethi's technical blog on Azure, SAP, and automation."
extra_css:
  - assets/custom.css
extra_javascript:
  - assets/custom.js
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
