# Devcontainer for MkDocs (Material theme)
FROM python:3.11-slim

# Install MkDocs and Material theme
RUN pip install --no-cache-dir mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-awesome-pages-plugin

# Set workdir
WORKDIR /workspace
